sudo: required
services: 
    - docker
script :
    - docker build -t soundaryamangesh/nodenew .
    - docker images soundaryamangesh/nodenew 

before deploy:
    - docker login -u soundaryamangesh -p Nagendrablock#244 


deploy: 
    provider: script
    script: docker push soundaryamangesh/nodenew
    on:
        branch : master
